### ISSUE TITLE
firstly! thank you for your work!

### ISSUE THREAD

**Issue by lbhqw** [tjr16/bathy_nn_learning#1]
is the dataset availble to acquire ? if no, sorry to bother you.

**Comment by lbhqw** [comment]
git lfs pull
batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.
error: failed to fetch some objects from 'https://github.com/tjr16/bathy_nn_learning.git/info/lfs'

**Comment by tjr16** [comment]
Thank you for your comment. Unfortunately, I am not purchasing any quota and thus the project is no longer maintained for now.
